config/routes.rb
Rails.application.routes.draw do
  root "trips#index"
  resources :users, :only => [:new, :create, :destroy]
  resources :trips, shallow: true do
    resources :locations, :only => [:index, :show, :create, :destroy], :controller => "location_pins"
    resources :posts
  end

  post '/users/login', to: 'users#login'
  get '/users/logout', to: 'users#logout'

  end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :location_pins
  has_many :trips, through: :location_pins

  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :name, presence: true
end

app/models/location_pin.rb
class LocationPin < ActiveRecord::Base
  belongs_to :trip
  belongs_to :location
  has_many :posts, dependent: :destroy

  validates :trip, presence: true
  validates :location, presence: true

  def coords
    location = self.location
    coords = { lat: location.latitude, lon: location.longitude }
  end

  def name
    self.location.name
  end
end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :user
  has_many :location_pins, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :location_pin

  validates :location_pin, :presence => true
  validates :title, presence: true, length: { maximum: 75,
    too_long: "%{count} characters is the maximum allowed" }
  validates :body, presence: true, length: { maximum: 1000,
    too_long: "%{count} characters is the maximum allowed" }

    def trip
      self.location_pin.trip
    end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :location_pins, dependent: :destroy
  has_many :locations, through: :location_pins
  has_many :posts, through: :location_pins

  validates :user, :presence => true
  validates :title, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  include BCrypt
  has_secure_password

  has_many :trips, dependent: :destroy
  has_many :location_pins, through: :trips
  has_many :posts, through: :trips

  validates :email, presence: true, :uniqueness => true, :format => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :password, presence: true, :length => { :minimum => 6, :message => "must be at least 6 characters" }
  validates :password_digest, presence: true, :length => { :minimum => 6, :message => "must be at least 6 characters" }

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(pass)
    @password = Password.create(pass)
    self.password_digest = @password
  end

  def self.authenticate(email, pass)
    @user = User.find_by_email(email)
    if @user && (@user.password == pass)
      @user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # Use :null_session with API.
  protect_from_forgery with: :null_session
  skip_before_filter :verify_authenticity_token, if: :json_request?


  def json_request?
    request.format.json?
  end

  def validate_user
    redirect_to new_user_path unless current_user
  end

end

app/controllers/location_pins_controller.rb
class LocationPinsController < ApplicationController
  before_action :validate_user

  def create
    trip = Trip.find params[:trip_id]
    @location_search_term = params[:location]

    return nil if location_params.nil?

    location = Location.find_or_create_by(location_params)
    location_pin = trip.location_pins.find_or_create_by(location: location)

    render json: { id: location_pin.id, name: location.name, coords: { lat: location.latitude, lon: location.longitude } }.to_json
  end

  def index
    all_pins = []
    @trip = Trip.find params[:trip_id]
    location_pins = @trip.location_pins

    location_pins.each do |pin|
      posts = []
      pin.posts.each do |post|
        posts << { post_id: post.id, post_title: post.title }
      end
      all_pins <<  { location_name: pin.location.name, coords: pin.coords, posts: posts }
    end
    p all_pins
    if request.xhr?
      render json: all_pins.to_json
    else
      @location_pins = location_pins
      render "trips/show"
    end
  end

  def show
    location_pin = LocationPin.find params[:id]
    @location = location_pin.location
    @posts = location_pin.posts
    @trip = location_pin.trip
  end

  def destroy
    LocationPin.destroy params[:id]
  end

  private

  def location_params
    geolocation = Geocoder.search(@location_search_term).first
    return nil if geolocation.nil? || geolocation.city.nil?
    coords = geolocation.coordinates
    full_location_name = geolocation.formatted_address.split(', ')
    city_state_name = "#{full_location_name[0]}, #{geolocation.state_code}"

    { name: city_state_name, latitude: coords[0], longitude: coords[1] }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :validate_user
  include PostHelper

  # def index
  #   @trip = Trip.find params[:trip_id]
  #   @locations = @trip.location_pins
  # end

  def new
    @trip = Trip.find params[:trip_id]
    @post = Post.new
  end

  def create
    location_name = params["post"]["location_pin"]
    trip = Trip.find params[:trip_id]
    location = Location.where(name: location_name).first
    location_pin = LocationPin.where(trip: trip, location: location).first

    @post = location_pin.posts.build post_params

    if @post.save
      redirect_to trip_path(trip.id)
    else
      render :"posts/new"
    end
  end

  def show
    @post = Post.find params[:id]
    @trip = @post.trip
    @location_pins = @post.trip.location_pins
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
  end

  def destroy
    post = Post.find params[:id]
    post.destroy
    redirect_to trip_posts
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def location_params
    location = params[:post][:location_pin]
    geolocation = Geocoder.search(location).first
    coords = geolocation.coordinates
    name = "#{geolocation.city}, #{geolocation.state_code}"

    params = { name: name, latitude: coords[0], longitude: coords[1] }
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :validate_user

  def index
    @trips = session[:user_id] ? Trip.all.where(user_id: session[:user_id]).order(created_at: :asc) : []
    @trip = Trip.new
  end

  def new
    @trip = Trip.new
  end

  def create
    location = params[:location]

    @trip = current_user.trips.create(title: location)

    render json: { trip_title: location, trip_id: @trip.id }.to_json
  end

  def show
    @trip = Trip.find(params[:id])
    @location_pins = @trip.location_pins
  end

  private

  def trip_params
    @trip.require(:trip).permit(:title)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def login
    @user = User.find_by(email: params[:user][:email])
    if @user && User.authenticate(params[:user][:email], params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    elsif @user && !User.authenticate(params[:user][:email], params[:user][:password])
      flash[:login_error] = "Incorrect email & password.  Please try again."
      redirect_to new_user_path
    else
      flash[:login_error] = "Email not found.  Please try again."
      redirect_to new_user_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:login_error] = "That email is already taken or you didn't enter a valid email/password combination. Please try again."
      redirect_to new_user_path
    end
  end

  def destroy
    User.destroy(params[:id])
    session.clear
  end

  def logout
    session.clear
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
      @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/post_helper.rb
module PostHelper
  def get_posts(category)
    category.posts
  end

  def get_post_titles(category)
    posts = get_posts(category)
    post_title = posts.map { |post| post.title }
  end
end

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li><%= link_to image_tag("geoscribe.png"), root_path, id: "nav-logo" %></li>
        </ul>
      </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-5">
          <% if current_user %>
            <p class="navbar-text navbar-right">Welcome <%= current_user.email %> <%= link_to "Logout", '/users/logout', html: {class: 'navbar-link'} %></p>
          <% else %>
            <p class="navbar-text navbar-right"><%= link_to "Login/Signup", '/users/new', html: {class: 'navbar-link'} %></p>
          <% end %>
        </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' %>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js' %>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyCRgPCj5H7JaEa7KaY1Pl13TUUTBcppL2Y' %>
  <%= javascript_include_tag 'http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js' %>
  <%= javascript_include_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/navbar" %>
  <%= yield %>

</body>
</html>

app/views/location_pins/show.html.erb
<div id="side" class="col-md-2">
  <div class="btn-group">
    <%= render partial: "trips/back_to_trip_new_post", locals: {trip: @trip} %>
  </div>
  <%= render partial: "trips/loc_posts", locals: {locationpins: @trip.location_pins } %>
  <div class="clearfix">&nbsp;</div>
</div>

<div class="col-md-10">
  <div class="page-header">
    <h1><%= @location.name %> <small>- Blog Posts</small> </h1>
  </div>
  <h3><%= @trip.title %></h3>
  <% @posts.reverse_each do |post| %>
    <div class="panel panel-info">
      <h4 class="panel-heading"><%= link_to post.title, post_path(post) %></h4>
      <div class="panel-body"><%= post.body %></div>
    </div>
  <% end %>
</div>

app/views/posts/_create.html.erb
<div class="modal" id="create-post" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">New Post for <%= locationname %></h4>
        </div>
        <div class="modal-body">
            <%= form_for @post, url: trip_posts_path do |f| %>

              <%= f.text_field :location_pin, value: locationname, hidden: true %>
              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', required: true  %>
              </div>
              <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, class: 'form-control', required: true  %>
              </div>

              <%= f.submit "Create Post", class: 'btn btn-primary btn-lg' %>
              <%= link_to 'Back', :back, class: 'btn btn-info btn-lg' %>
          <% end %>
        </div>

      <div class='clearfix'>&nbsp;</div>
    </div>
  </div>
</div>

<script type="text/javascript">
 $('#create-post').modal('show');
</script>

app/views/posts/index.html.erb
<div id="side" class="col-md-2">
  <%= link_to "All Trips", trips_path, class: "btn" %>
  <h2><%= @trip.title %></h2>
  <hr>
  <% @locations.reverse_each do |location| %>
     <h3 class="location-names"><%= location.name %></h3>
     <% get_posts(location).each do |post| %>
      <%= link_to post.title, post_path(post) %>
     <% end %>
  <% end %>
  <div class="clearfix">&nbsp;</div>
</div>

app/views/posts/new.html.erb
<div class="col-md-12" style="padding-left:0">
  <div id='map-canvas'></div>
  <%= render partial: "create", locals: {locationname: params[:locationname]}  %>
</div>

app/views/posts/show.html.erb
<div id="side" class="col-md-2">
  <div class="btn-group">
    <%= render partial: "trips/back_to_trip_new_post", locals: {trip: @trip} %>
  </div>
  <div id='trip-show-container'>
    <%= render partial: "trips/loc_posts", locals: {locationpins: @location_pins} %>
  </div>
  <div class="clearfix">&nbsp;</div>
</div>
<div class="col-md-10">
  <div class="panel panel-info">
    <h1 class="panel-heading"><%= @post.title %></h1>
    <div class="panel-body"><%= @post.body %></div>
  </div>
</div>

app/views/trips/_back_to_trip_new_post.html.erb
<br>
<%= link_to content_tag(:button, 'Back to Map', class: "btn btn-primary"),  trip_path(trip) %>
<br>
<br>

app/views/trips/_loc_posts.html.erb
<% locationpins.reverse_each do |locationpin| %>
    <div class="panel panel-default panel-relative">
     <div class="panel-heading"><h3 class='h3-location'>
      <%= link_to locationpin.name, location_path(locationpin) %></h3></div>

      <%= button_to '+', new_trip_post_path(locationpin.trip.id), form_class: "label label-info add-post-label", params: { :'locationname' => locationpin.location.name }, method: :get %>
      <ul class="list-group">
        <% get_posts(locationpin).reverse_each do |post| %>
          <li class="list-group-item"><%= link_to post.title, post_path(post) %></li>
       <% end %>
      </ul>
    </div>
<% end %>

app/views/trips/index.html.erb
<div id="side" class="col-md-2">
  <h1>Trips</h1>
  <hr>
  <div class="btn-group">
    <h4 style="float:left;">Add Trip</h4>
    <br>
      ￼<%= form_tag("/", method: "get", class: 'input-group', id: 'trip-create')  do %>
        <%= text_field_tag('location', nil, placeholder: "Trip Title", class: 'form-control') %>
        <span class='input-group-btn'><%= submit_tag("+", class: 'btn btn-warning') %></span>
      <% end %>
      <br>
  </div>
  <div id='sidebar-new-trip'></div>
  <ul class='list-group'>
    <% @trips.each do |trip| %>
      <li class="list-group-item"><%= link_to trip.title, trip_path(trip), data: { :'trip-id' => trip.id} %></li>
    <% end %>
  </ul>
  <div class="clearfix">&nbsp;</div>
</div>

<div id="map" class="col-md-10">
   <div id="map-canvas"></div>
</div>

app/views/trips/new.html.erb
<h1>Create New Trip</h1>

<%= form_for(@trip, remote: true) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.submit %>

<% end %>

app/views/trips/show.html.erb
<div id="side" class="col-md-2">
  <h2><%= @trip.title %></h2>
  <div class="btn-group">
    <%= link_to content_tag(:button, 'Back to Trips', class: "btn btn-primary"), trips_path, remote: true %>
      <br>
      <hr>
      <h3 class="h3-location">Add location</h3>
      ￼<%= form_tag("/", method: "get", class: 'input-group', id: 'location-create')  do %>
        <%= text_field_tag('location', nil, placeholder: "City, State", class: 'form-control') %>
        <span class='input-group-btn'><%= submit_tag("+", class: 'btn btn-warning') %></span>
      <% end %>
      <h4 style="float:right; margin-top: 1.5em">Add Post</h4>
  </div>
  <div id='sidebar-new-trip'></div>
  <div id='trip-show-container'>
    <%= render partial: "loc_posts", locals: {locationpins: @location_pins} %>
  </div>
  <div class="clearfix">&nbsp;</div>
</div>

<div id="map" class="col-md-10" data-trip-id="<%= @trip.id %>">
   <div id="map-canvas"></div>
</div>

<script>Map.loadTripPins(<%= @trip.id %>)</script>

app/views/users/_login.html.erb
<%= form_for @user, url: "/users/login" do |f| %>
  <div class="form-group">
    <%= f.label :email, "Email: " %>
    <%= f.text_field :email, placeholder: 'LizGilbert@email.com', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password, "Password: " %>
    <%= f.password_field :password, placeholder: '******', class: 'form-control', required: true %>
  </div>
  <%= f.submit "Log In", class: 'btn btn-info btn-lg' %>
<% end %>

app/views/users/_signup.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email, "Email: " %>
    <%= f.text_field :email, placeholder: "LizGilbert@email.com", class: 'form-control' %>
  </div>
  <div class="form-group">  
    <%= f.label :password, "Password: " %>
    <%= f.password_field :password, placeholder: "Must be at least 6 characters", class: 'form-control', required: true %>
  </div>
    <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Password: " %>
    <%= f.password_field :password_confirmation, placeholder: "Enter password again", class: 'form-control', required: true %>
  </div>
  <%= f.submit "Create Account", class: 'btn btn-lg btn-warning' %>
<% end %>

<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div id="user_index">
  <div id="map" class="col-md-10">

      <div class="modal" id="login-modal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
          <div class="modal-content">


              <% if flash[:login_error] %>
                <div class="alert alert-danger">
                  <%= flash[:login_error]%>
                </div>
              <% end %>

            <div class="col-sm-6">
              <div class="modal-header">
                <h4 class="modal-title">Create Account</h4>
              </div>
              <div class="modal-body">
                <%= render "signup" %>
              </div>
            </div>

             <div class="col-sm-6">
              <div class="modal-header">
                <h4 class="modal-title">Login</h4>
              </div>
              <div class="modal-body">
                <%= render "login" %>
              </div>
            </div>

          <div class='clearfix'>&nbsp;</div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

  </div>
  <div class="clearfix">&nbsp;</div>
</div>
<script type="text/javascript">
$('#login-modal').modal('show');
</script>